### ISSUE TITLE
Is it possible to migrate this to FC 0.17 as well ?

### ISSUE THREAD

**Issue by luzpaz** [mahaarbo/ARBench#1]

**Comment by mahaarbo** [comment]
For my interests, there's two really good features in FC 0.17: the faster STEP file handling, and the new way of doing placements. Whoever redid the STEP import did a good job. 
So once the stable release is out I'll look into migrating.

**Comment by luzpaz** [comment]
officially it's not out but from an infrastructure point it's not going to change much from the current 0.17 The new release is due sometime in Feb. I'm just saying you can start. 
You can run a blame on the source to see who improved the code. You are right it did get a more love in 0.17

**Comment by mahaarbo** [comment]
Cool! I'll look into it.

**Comment by mahaarbo** [comment]
The bug that caused problems with closing the featureframecreator has now been removed. Much of the functionality now works with FreeCAD >0.17. But it sometimes messes up placements because I haven't gotten into how the new placement works.

**Comment by luzpaz** [comment]
Great! Please ask on the forum. Also the release for 0.18 is coming up (this ticket is for 0.17 ;)

**Comment by mahaarbo** [comment]
#3
